apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-veloz-config
  namespace: pedidos-veloz
data:
  PEDIDOS_SERVICE_URL: "http://pedidos:8001"
  PAGAMENTOS_SERVICE_URL: "http://pagamentos:8002"
  ESTOQUE_SERVICE_URL: "http://estoque:8003"
