apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: pedidos-veloz
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos
  namespace: pedidos-veloz
spec:
  selector:
    app: pedidos
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos
  namespace: pedidos-veloz
spec:
  selector:
    app: pagamentos
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: estoque
  namespace: pedidos-veloz
spec:
  selector:
    app: estoque
  ports:
    - port: 8003
      targetPort: 8003
